### ISSUE TITLE
Scratchpad TODO

### ISSUE THREAD

**Issue by DrearyWillow** [MellowKyler/pdfp#12]
- [ ] Consider Pathlib over os. also maybe there's a pyside6 way too. 
- [x] OCR postprocessing progress bar. maybe not 100% while working? artificially limit to 90%?
- [x] Maybe relocate button_toggle for ocr for the time being. it unlocks before native ocr can run process_finished.
- [x] Rename option in file tree (only filename itself, not dir)
- [ ] reorder file tree items (drag?)
- [ ] make keypressevent a case statement
- [ ] docstrings for new functions
- [ ] reorder file_tree_widget functions in more readable way
- [ ] refactor operation calls to not rely on a floating variable - instantiate each time (i tried and its hard and i think its because OOP and i don't wanna fuck with it)
- [ ] make a operation Class and have operations inherit. common methods inside operation class
